#!/bin/sh
#
# @name Rover
#

. ${R}etc/init.d/rc.rover_defaults

# 1-sigma IMU gyro switch-on bias rad/s
param set-default EKF2_GBIAS_INIT 0.01

# 1-sigma tilt angle in deg uncertanity after gravity vector alingment
param set-default EKF2_ANGERR_INIT 0.01

# Magnetometer fusion 0: Automatic, 1: Magnetic heading, 2: 3-axis, 3: VTOL custom, 4: MC Custom, 5: None
param set-default EKF2_MAG_TYPE 1


# The minimal distance in meters that next way point will activate
param set-default GND_L1_DIST 5

# Defines the tracking point ahead of the rover it's following
param set-default GND_L1_PERIOD 10

# Close loop with gps speed set to 1, Open loop set to 0
param set-default GND_SP_CTRL_MODE 1

# PID speed coefficient
param set-default GND_SPEED_P 0.25
param set-default GND_SPEED_I 3
param set-default GND_SPEED_D 0.001

# Anti wind-up parameter %m/s
param set-default GND_SPEED_IMAX 0.125

# Trim ground speed m/s
param set-default GND_SPEED_TRIM 4

# Throttle parameters in percentage %
param set-default GND_SPEED_THR_SC 1
param set-default GND_THR_CRUISE 0.3
param set-default GND_THR_MAX 0.5
param set-default GND_THR_MIN 0

# Minimal altiture to arm in meters
param set-default MIS_LTRMIN_ALT 0.01
param set-default MIS_TAKEOFF_ALT 0.01

# Acceptable waypoint accuracy in meters
param set-default NAV_ACC_RAD 0.5
param set-default NAV_LOITER_RAD 2

# Enable Airspeed check circuit breaker because Rovers will have no airspeed sensor
param set-default CBRK_AIRSPD_CHK 162128

# Differential drive acts like ackermann steering with a maximum turn angle of 60 degrees, or pi/3 radians
param set-default GND_MAX_ANG 0.6
param set-default GND_WHEEL_BASE 2.0

# Battery cells
param set-default BAT1_N_CELLS 4

# Manual control parameters
# param set-default RC2_TRIM 1000
# param set-default COM_FLTMODE1 2
# param set-default RC_MAP_ROLL 1
# param set-default RC_MAP_THROTTLE 2
# param set-default RC_MAP_PITCH 3
# param set-default RC_MAP_YAW 4
# param set-default RC_MAP_FLTMODE 5
# param set-default RC_CHAN_CNT 8

# Configure this as rover
set MAV_TYPE 10

# Set mixer
set MIXER_FILE etc/mixers-sitl/rover_ackermann_sitl.main.mix