#!/bin/sh
#
# @name Differancial Wheeled Rover
#

. ${R}etc/init.d/rc.rover_defaults

# 1-sigma IMU gyro switch-on bias rad/s
# param set-default EKF2_GBIAS_INIT 0.01

# 1-sigma tilt angle in deg uncertanity after gravity vector alingment
# param set-default EKF2_ANGERR_INIT 0.01

# Magnetometer fusion 0: Automatic, 1: Magnetic heading, 2: 3-axis, 3: VTOL custom, 4: MC Custom, 5: None
# param set-default EKF2_MAG_TYPE 1


# The minimal distance in meters that next way point will activate
param set-default GND_L1_DIST 5

# Close loop with gps speed set-default to 1, Open loop set-default to 0
param set-default GND_SP_CTRL_MODE 1

# PID speed coefficient
param set-default GND_SPEED_P 0.123
param set-default GND_SPEED_I 0.0
param set-default GND_SPEED_D 0.123

# Anti wind-up parameter %m/s
param set-default GND_SPEED_IMAX 0.125
param set-default GND_MAN_Y_MAX 10.0

# Gain to map speed %m/s
param set-default GND_SPEED_THR_SC 1

# Trim ground speed m/s
param set-default GND_SPEED_TRIM 1

# Throttle parameters in percentage %
param set-default GND_THR_CRUISE 0.3
param set-default GND_THR_MAX 0.2
param set-default GND_THR_MIN 0

# Minimal altiture to arm in meters
param set-default MIS_LTRMIN_ALT 0.01
param set-default MIS_TAKEOFF_ALT 0.01

# Acceptable waypoint accuracy in meters
param set-default NAV_ACC_RAD 0.5
param set-default NAV_LOITER_RAD 2

# Enable Airspeed check circuit breaker because Rovers will have no airspeed sensor
param set-default CBRK_AIRSPD_CHK 162128

# Because this is differential drive, it can make a turn with radius 0.
# This corresponds to a turn angle of pi radians.
# If a special case is made for differential-drive, this will need to change.
# param set-default GND_MAX_ANG 3.142
param set-default GND_MAX_ANG 0.6
param set-default GND_WHEEL_BASE 0.02

# Battery cells
param set-default BAT1_N_CELLS 4

# Manual control parameters
param set-default RC2_TRIM 1000
param set-default COM_FLTMODE1 2
param set-default RC_MAP_ROLL 1
param set-default RC_MAP_THROTTLE 2
param set-default RC_MAP_PITCH 3
param set-default RC_MAP_YAW 4
param set-default RC_MAP_FLTMODE 5
param set-default RC_CHAN_CNT 8

# Configure this as rover
set MAV_TYPE 10

# set-default mixer
set MIXER_FILE etc/mixers-sitl/rover_diff_sitl.main.mix
