#!/bin/sh
#
# @name Balamut i Oborot
#
# @type Quadrotor X
#

. ${R}etc/init.d/rc.mc_defaults

###############################################
# Attitude & rate gains
###############################################
# Roll
param set-default MC_ROLL_P 6.5
param set-default MC_ROLLRATE_P 0.0630
param set-default MC_ROLLRATE_I 0.0840
param set-default MC_ROLLRATE_D 0.0014
param set-default MC_ROLLRATE_MAX 220

# Pitch
param set-default MC_PITCH_P 6.5
param set-default MC_PITCHRATE_P 0.0660
param set-default MC_PITCHRATE_I 0.0860
param set-default MC_PITCHRATE_D 0.0014
param set-default MC_PITCHRATE_MAX 220

# Yaw
param set-default MC_YAW_P 6.5
param set-default MC_YAWRATE_P 0.07
param set-default MC_YAWRATE_I 0.06
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0
param set-default MC_YAWRATE_MAX 200

###############################################
# Multirotor Position Gains
###############################################
param set-default MPC_ACC_HOR 8
param set-default MPC_THR_MIN 0.06
param set-default MPC_THR_HOVER 0.3
# altitude control gains
param set-default MPC_Z_P 1
param set-default MPC_Z_VEL_P_ACC 4
param set-default MPC_Z_VEL_I_ACC 0.4
# position control gains
param set-default MPC_XY_P 0.9500
param set-default MPC_XY_VEL_P_ACC 1.8
param set-default MPC_XY_VEL_I_ACC 0.4
param set-default MPC_XY_VEL_D_ACC 0.2
# etc gains
param set-default MPC_TKO_RAMP_T 0.0
param set-default MPC_TKO_SPEED 1.5
param set-default MPC_VEL_MANUAL 5


#####################################
# EKF
#####################################
# fusion: gps + flow + vis pos + vis yaw
param set-default EKF2_AID_MASK 27
param set-default EKF2_OF_DELAY 0
param set-default EKF2_OF_QMIN 10
param set-default EKF2_OF_N_MIN 0.05
param set-default EKF2_OF_N_MAX 0.2

# height est: 0 = baro, 1 = gps, 2 = range, 3 = vision
param set-default EKF2_HGT_MODE 2
# maximum fusion in (m) for the distance sensor
param set-default EKF2_RNG_A_HMAX 4
param set-default EKF2_EVA_NOISE 0.1
param set-default EKF2_EVP_NOISE 0.1
param set-default EKF2_EV_DELAY 0

# LPE: Flow-only mode
param set-default LPE_FUSION 242
param set-default LPE_FAKE_ORIGIN 1

# ALT Mode: 0 alt following, 1 terrain following, 2 terrain hold
param set-default MPC_ALT_MODE 2

# # Optical Flow parameters
param set-default SENS_FLOW_ROT 0
param set-default SENS_FLOW_MINHGT 0.0
param set-default SENS_FLOW_MAXHGT 4.0
param set-default SENS_FLOW_MAXR 10.0

# Filter settings
param set-default IMU_DGYRO_CUTOFF 90
param set-default IMU_GYRO_CUTOFF 100

# Minimum take off altitude
param set-default MIS_TAKEOFF_ALT 1.1

# Time out of auto disarm
param set-default COM_DISARM_LAND 1.0

# enable offboard flights without rc
param set-default COM_RCL_EXCEPT 4

# avoidance
param set-default COM_OBS_AVOID 1
param set-default MPC_XY_CRUISE 5.0

# Manual control parameters
param set-default RC2_TRIM 1000
param set-default COM_FLTMODE1 2
param set-default RC_MAP_ROLL 1
param set-default RC_MAP_THROTTLE 2
param set-default RC_MAP_PITCH 3
param set-default RC_MAP_YAW 4
param set-default RC_MAP_FLTMODE 5
param set-default RC_CHAN_CNT 8

# Set to Quadrotor
set MAV_TYPE 2

set MIXER quad_x