#!/bin/sh
#
# @name Differancial Balancing Robot
# @type Rover
# @class Rover

. ${R}etc/init.d/rc.rover_defaults

# Waypoint parameters
param set-default GND_L1_DIST 5

# GND_SP_CTRL_MODE 0 - open loop control, 1 close loop control
param set-default GND_SP_CTRL_MODE 1

# PID
param set-default GND_SPEED_D 3
param set-default GND_SPEED_I 0.001
param set-default GND_SPEED_IMAX 0.125
param set-default GND_SPEED_P 0.25
param set-default GND_SPEED_THR_SC 1
param set-default GND_SPEED_TRIM 4

# Trottle
param set-default GND_THR_CRUISE 0.3
param set-default GND_THR_MAX 0.5
param set-default GND_THR_MIN 0

# Altitude
param set-default MIS_LTRMIN_ALT 0.01
param set-default MIS_TAKEOFF_ALT 0.01

# Navigation
param set-default NAV_ACC_RAD 0.5
param set-default NAV_LOITER_RAD 2

# Enable Airspeed check circuit breaker because Rovers will have no airspeed sensor
param set-default CBRK_AIRSPD_CHK 162128

# Because this is differential drive, it can make a turn with radius 0.
# This corresponds to a turn angle of pi radians.
# If a special case is made for differential-drive, this will need to change.
param set-default GND_MAX_ANG 0.6
param set-default GND_WHEEL_BASE 0.015

# Dynamic control allocation
param set-default SYS_CTRL_ALLOC 1

# Select rover type
param set-default CA_AIRFRAME 6

# Bidirqactional or reverse motors
param set-default CA_R_REV 3

# Servos
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 101
param set-default PWM_MAIN_FUNC6 102
param set-default PWM_MAIN_FUNC7 102

# Manual control
param set-default COM_RC_IN_MODE 3
param set-default RC2_TRIM 1000
param set-default COM_FLTMODE1 2
param set-default RC_MAP_ROLL 1
param set-default RC_MAP_THROTTLE 2
param set-default RC_MAP_PITCH 3
param set-default RC_MAP_YAW 4
param set-default RC_MAP_FLTMODE 5
param set-default RC_CHAN_CNT 8

# Failsafe disable
# param set-default NAV_DLL_ACT = 0
# param set-default NAV_RCL_ACT = 3

# enable offboard flights without rc
param set-default COM_RCL_EXCEPT 4

# Set to rover
set MAV_TYPE 10

# Mixer
set MIXER_FILE skip