#!/bin/sh
#
# @name Typhoon H480 SITL
#
# @type Hexarotor x
#

. ${R}etc/init.d/rc.mc_defaults

###############################################
# Attitude & rate gains
###############################################
# Roll
param set-default MC_ROLLRATE_P 0.1700
param set-default MC_ROLLRATE_I 0.02000
param set-default MC_ROLLRATE_D 0.030
param set-default MC_ROLL_P 5.41

# Pitch
param set-default MC_PITCHRATE_P 0.1800
param set-default MC_PITCHRATE_I 0.02000
param set-default MC_PITCHRATE_D 0.030
param set-default MC_PITCH_P 5.22

# Yaw
# param set-default MC_YAWRATE_P 0.0017
# param set-default MC_YAWRATE_I 0.0025
# param set-default MC_YAWRATE_D 0.0002
# param set-default MC_YAW_P 0.03


###############################################
# Multirotor Position Gains
###############################################
# position control gains
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_P_ACC 6

# Return altitude
param set-default RTL_DESCEND_ALT 10

# Camera control
param set-default TRIG_INTERFACE 3
param set-default TRIG_MODE 4

# Gimbal
param set-default MNT_MODE_IN 4
param set-default MNT_MODE_OUT 2
param set-default MAV_PROTO_VER 2

# avoidance
param set-default COM_OBS_AVOID 1
param set-default MPC_XY_CRUISE 5.0

# enable offboard flights without rc
param set-default COM_RCL_EXCEPT 4

# Manual control parameters
param set-default RC2_TRIM 1000
param set-default COM_FLTMODE1 2
param set-default RC_MAP_ROLL 1
param set-default RC_MAP_THROTTLE 2
param set-default RC_MAP_PITCH 3
param set-default RC_MAP_YAW 4
param set-default RC_MAP_FLTMODE 5
param set-default RC_CHAN_CNT 8

# Set to Hexacopter
set MAV_TYPE 13

set MIXER hexa_x