version: '3'
services:
    ubuntu-avoidance:
        build:
            context: ../../
            dockerfile: docker/demo/ubuntu/Dockerfile
        privileged: true
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
